### PR TITLE
Get browser from Jupyter config

### LINKED ISSUE #27: Default browser
It would be nice if nbopen opens the notebook via the browser set in the jupyter profile:
```c.NotebookApp.browser = ``` instead of the users default browser. 

In order to not mix up my notebooks with my other browsing tabs, I use chromium for the notebooks, and firefox for the other activities.

As I quick fix on unix, I changed in nbopen.desktop the exec line:

```Exec=env BROWSER=chromium-browser nbopen %f```

### PR DESCRIPTION
**Pull request by takluyver**
Fixes #27 

@vascotenner, can you test this?

### CODE REVIEW

**Comment by vascotenner** [comment]
Only when no server is running this works (as it did before). When there is an server running, it still opens the default browser. When I check (python2.7), na.browser is empty.

**Comment by takluyver** [comment]
How about now?

**Comment by vascotenner** [comment]
This works, thank you very much for the fast response!

**Comment by takluyver** [comment]
No problem, thanks for testing it!

**Pull request merged**
